version: '3.5'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    image: nestjs_app
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      db:
       condition: service_healthy     
    volumes:
      - ./src:/app/src
